server:
  port: 18091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  elasticsearch:
    rest:
      uris: http://192.168.136.129:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.136.129
    port: 5672
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true