server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.136.129
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.129:3306/guli_cart
    username: root
    password: 123456Abc@
  task:
    execution:
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.136.129
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: E:\workspace\project-0821\rsa\rsa.pub
  cookieName: GMALLL-TOKEN
  userKey: userKey
  expire: 864000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
